apiVersion: v1
kind: Service
metadata:
  name: todo-web
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007 # 특정 포트를 지정할 수 있습니다 (30000-32767 범위 내에서).
  selector:
    app: todo-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          env:
            - name: Logging__LogLevel__Default
              value: Warning
