apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-1
spec:
  selector:
    matchLabels:
      app: my-test-1
  template:
    metadata:
      labels:
        app: my-test-1
    spec:
      containers:
        - name: web
          image: kiamol/ch02-hello-kiamol

---
apiVersion: v1
kind: Service
metadata:
  name: my-test-1
spec:
  selector:
    app: my-test-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # 또는 NodePort, ClusterIP 등 필요에 따라 변경 가능
