apiVersion: batch/v1
kind: Job
metadata:
  name: nginx
  labels:
    kiamol: ch08-lab
    app: nginx
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: kiamol/ch03-sleep
          name: calc
          command:
            [
              "sh",
              "-c",
              "du -h /nginx0/access.log /nginx1/access.log /nginx2/access.log",
            ]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx0
              mountPath: /nginx0/
            - name: nginx1
              mountPath: /nginx1/
            - name: nginx2
              mountPath: /nginx2/
      volumes:
        - name: nginx0
          persistentVolumeClaim:
            claimName: logs-nginx-0
        - name: nginx1
          persistentVolumeClaim:
            claimName: logs-nginx-1
        - name: nginx2
          persistentVolumeClaim:
            claimName: logs-nginx-2
